spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC
    username: your_db_login
    password: your_db_password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8087